/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 0

/run/initialize

/process/had/rdm/nucleusLimits 16 20 8 12
/process/had/rdm/thresholdForVeryLongDecayTime 1e19 s

/process/em/auger false
/process/em/pixe false
/process/em/fluo false

/DetSys/world/material Vacuum
#/DetSys/det/addGriffinForward 16
/DetSys/det/addRCMP

/Histo/RecordGun true

#/DetSys/gun/BeamSpot 0.5 mm
#/DetSys/gun/coneMaxAngle 90 deg
#/DetSys/gun/coneMinAngle 0 deg
#/DetSys/gun/position 0.0 0.0 1.54945 mm
#/DetSys/gun/position 0.0 0.0 3.9 mm
/DetSys/gun/position 0.0 0.0 1.99945 mm

#/gun/particle ion
#/gun/ion 12 20
/gun/particle proton
#/gun/particle e+

/DetSys/gun/efficiencyEnergy 1. MeV
#/DetSys/gun/efficiencyEnergy 0. MeV

/run/beamOn 1000000
