/run/initialize

/DetSys/world/material Vacuum
/DetSys/det/addGriffinForward 16
/DetSys/det/addRCMP

/tracking/storeTrajectory 1
/vis/open OGL
#/vis/open OGLIQt
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/axes 0 0 0 10 cm
/vis/viewer/set/targetPoint 0 0 0 m
/vis/viewer/set/style surface
/vis/scene/endOfEventAction accumulate 10000
/Histo/RecordGun true
/DetSys/gun/BeamSpot 5 mm
/DetSys/gun/coneMaxAngle 90 deg
/DetSys/gun/coneMinAngle 0 deg
#/DetSys/gun/position 0.0 0.0 0.0 cm
/gun/particle alpha
/DetSys/gun/efficiencyEnergy 5.8 MeV
#/run/beamOn 2000
